name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Restore state from secret
        env:
          STATE: ${{ secrets.TF_STATE }}
        run: |
          echo "$STATE" | base64 -d > cluster/terraform.tfstate

      - name: Terraform Init
        working-directory: ./cluster
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./cluster
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: terraform destroy -auto-approve -var="do_token=${DO_TOKEN}"
