name: Terraform Destroy

on:
  workflow_dispatch:   # manual trigger only

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: production   # add approvals here if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: ./cluster
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./cluster
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: terraform destroy -auto-approve -var="do_token=${DO_TOKEN}"
