name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: ./cluster
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ./cluster
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: terraform apply -auto-approve -var="do_token=${DO_TOKEN}"

      - name: Encode and Push State to Secret
        working-directory: ./cluster
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          STATE=$(base64 -w 0 terraform.tfstate)
          gh secret set TF_STATE --body "$STATE"
